<script setup lang="ts">
// Auto-generated by Forge from a Claude proposal. Source: hand-written.
// Safe to hand-edit — port-icons.mjs only overwrites icons sourced from animate-ui.
import { computed } from 'vue'
import { motion, type Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import {
  getVariants,
  hasOwnTriggers,
  useAnimateIconContext,
  type IconTriggerProps,
} from '../core/context'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations = {
  default: {
    wand: {
      initial: {
        x: 0,
        y: 0,
        rotate: 0,
      },
      animate: {
        x: [0, -0.6, 0.5, -0.4, 0.4, -0.3, 0.2, 0],
        y: [0, 0.4, -0.5, 0.3, -0.3, 0.2, -0.1, 0],
        rotate: [0, -1.5, 1.2, -1, 0.8, -0.5, 0.3, 0],
        transformOrigin: "19.5px 4.5px",
        transition: {
          duration: 1.1,
          ease: "easeInOut",
        },
      },
    },
    sparkleA: {
      initial: {
        scale: 0,
        opacity: 0,
        rotate: -45,
      },
      animate: {
        scale: [0, 1.3, 1],
        opacity: [0, 1, 1],
        rotate: [-45, 0, 0],
        transition: {
          duration: 0.45,
          delay: 0.15,
          ease: "easeOut",
        },
      },
    },
    sparkleB: {
      initial: {
        scale: 0,
        opacity: 0,
        rotate: -45,
      },
      animate: {
        scale: [0, 1.3, 1],
        opacity: [0, 1, 1],
        rotate: [-45, 0, 0],
        transition: {
          duration: 0.45,
          delay: 0.35,
          ease: "easeOut",
        },
      },
    },
    sparkleC: {
      initial: {
        scale: 0,
        opacity: 0,
        rotate: -45,
      },
      animate: {
        scale: [0, 1.3, 1],
        opacity: [0, 1, 1],
        rotate: [-45, 0, 0],
        transition: {
          duration: 0.45,
          delay: 0.55,
          ease: "easeOut",
        },
      },
    },
  } satisfies Record<string, Variants>,
} satisfies Record<string, Record<string, Variants>>

const variants = getVariants(animations)
const { current, notifyComplete } = useAnimateIconContext()
const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <WandSparkles :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <motion.svg
    v-else
    overflow="visible"
    style="user-select: none; -webkit-user-select: none"
    xmlns="http://www.w3.org/2000/svg"
    :width="props.size"
    :height="props.size"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    :stroke-width="props.strokeWidth"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
    <motion.path
      d="m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72"
      :variants="variants.wand"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="m14 7 3 3"
      :variants="variants.wand"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M5 6v4"
      style="transform-origin: 5px 8px"
      :variants="variants.sparkleA"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M7 8H3"
      style="transform-origin: 5px 8px"
      :variants="variants.sparkleA"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M10 2v2"
      style="transform-origin: 10px 3px"
      :variants="variants.sparkleB"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M11 3H9"
      style="transform-origin: 10px 3px"
      :variants="variants.sparkleB"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M19 14v4"
      style="transform-origin: 19px 16px"
      :variants="variants.sparkleC"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M21 16h-4"
      style="transform-origin: 19px 16px"
      :variants="variants.sparkleC"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
  </motion.svg>
</template>
