<script setup lang="ts">
// Multi-variant icon. The original animate-ui / hand-written silhouette ships
// as `default` (plus any extra named animations the base SFC carried —
// `blink`, `wink`, `pulse`, etc.); the pqoqubbw/lucide-animated silhouette
// ships as `alt`. Element graphs differ across variants, so we delegate to
// `<MultiVariantIcon>` rather than the standard hand-templated layout.
//
// Generated by scripts/port-pqoqubbw-icons.mjs (multi-variant merge path).
// Hand-edits survive port reruns — the script preserves SFCs that already
// host an `alt` variant via this path.
import { computed } from 'vue'
import type { Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import MultiVariantIcon from '../core/MultiVariantIcon.vue'
import { hasOwnTriggers, type IconTriggerProps } from '../core/context'
import type { MultiVariantAnimations } from '../core/element-types'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations: MultiVariantAnimations = {
  default: {
    elements: [
      { tag: "line", attrs: { x1: 6, y1: 18, x2: 18, y2: 6 }, key: "line1" },
      { tag: "line", attrs: { x1: 6, y1: 6, x2: 18, y2: 18 }, key: "line2" },
    ],
    variants: {
    line1: {
      initial: {
        rotate: 0,
        transition: { ease: 'easeInOut', duration: 0.4 },
      },
      animate: {
        rotate: 90,
        transition: { ease: 'easeInOut', duration: 0.4 },
      },
    },
    line2: {
      initial: {
        rotate: 0,
        transition: { ease: 'easeInOut', duration: 0.4, delay: 0.1 },
      },
      animate: {
        rotate: 90,
        transition: { ease: 'easeInOut', duration: 0.4, delay: 0.1 },
      },
    },
  } as Record<string, Variants>,
  },
  plus: {
    elements: [
      { tag: "line", attrs: { x1: 6, y1: 18, x2: 18, y2: 6 }, key: "line1" },
      { tag: "line", attrs: { x1: 6, y1: 6, x2: 18, y2: 18 }, key: "line2" },
    ],
    variants: {
    line1: {
      initial: {
        rotate: 0,
        x1: 6,
        y1: 18,
        x2: 18,
        y2: 6,
        transition: { ease: 'easeInOut', duration: 0.3, delay: 0.1 },
      },
      animate: {
        rotate: 45,
        x1: 7.1,
        y1: 16.9,
        x2: 16.9,
        y2: 7.1,
        transition: { ease: 'easeInOut', duration: 0.3, delay: 0.1 },
      },
    },
    line2: {
      initial: {
        rotate: 0,
        x1: 6,
        y1: 6,
        x2: 18,
        y2: 18,
        transition: { ease: 'easeInOut', duration: 0.3 },
      },
      animate: {
        rotate: 45,
        x1: 7.1,
        y1: 7.1,
        x2: 16.9,
        y2: 16.9,
        transition: { ease: 'easeInOut', duration: 0.3 },
      },
    },
  } as Record<string, Variants>,
  },
  alt: {
    elements: [
      { tag: "path", attrs: { d: "M18 6 6 18" }, key: "path" },
      { tag: "path", attrs: { d: "m6 6 12 12" }, key: "path" },
    ],
    variants: {
    path: {
  initial: {
    opacity: 1,
    pathLength: 1,
  },
  animate: {
    opacity: [0, 1],
    pathLength: [0, 1],
  },
},
  } as Record<string, Variants>,
  },
}

const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <X :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <MultiVariantIcon
    v-else
    :animations="animations"
    :size="props.size"
    :strokeWidth="props.strokeWidth"
  />
</template>
