<script setup lang="ts">
// Multi-variant icon. The original animate-ui / hand-written silhouette ships
// as `default` (plus any extra named animations the base SFC carried —
// `blink`, `wink`, `pulse`, etc.); the pqoqubbw/lucide-animated silhouette
// ships as `alt`. Element graphs differ across variants, so we delegate to
// `<MultiVariantIcon>` rather than the standard hand-templated layout.
//
// Generated by scripts/port-pqoqubbw-icons.mjs (multi-variant merge path).
// Hand-edits survive port reruns — the script preserves SFCs that already
// host an `alt` variant via this path.
import { computed } from 'vue'
import type { Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import MultiVariantIcon from '../core/MultiVariantIcon.vue'
import { hasOwnTriggers, type IconTriggerProps } from '../core/context'
import type { MultiVariantAnimations } from '../core/element-types'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations: MultiVariantAnimations = {
  default: {
    elements: [
      { tag: "g", attrs: {}, key: "group", children: [
        { tag: "path", attrs: { d: "M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" }, key: "path" },
        { tag: "line", attrs: { x1: "16", y1: "10", x2: "16", y2: "10" }, key: "line1" },
        { tag: "line", attrs: { x1: "12", y1: "10", x2: "12", y2: "10" }, key: "line2" },
        { tag: "line", attrs: { x1: "8", y1: "10", x2: "8", y2: "10" }, key: "line3" },
      ] },
    ],
    variants: {
    group: {
      initial: {
        rotate: 0,
      },
      animate: {
        transformOrigin: 'bottom left',
        rotate: [0, 8, -8, 2, 0],
        transition: {
          ease: 'easeInOut',
          duration: 0.8,
          times: [0, 0.4, 0.6, 0.8, 1],
        },
      },
    },
    path: {},
    line1: {
      initial: {
        y1: 10,
        y2: 10,
        transition: { ease: 'easeInOut', duration: 0.6 },
      },
      animate: {
        y1: [10, 8.5, 10],
        y2: [10, 11.5, 10],
        transition: { ease: 'easeInOut', duration: 0.6, delay: 0.2 },
      },
    },
    line2: {
      initial: {
        y1: 10,
        y2: 10,
        transition: { ease: 'easeInOut', duration: 0.6 },
      },
      animate: {
        y1: [10, 8.5, 10],
        y2: [10, 11.5, 10],
        transition: { ease: 'easeInOut', duration: 0.6, delay: 0.1 },
      },
    },
    line3: {
      initial: {
        y1: 10,
        y2: 10,
        transition: { ease: 'easeInOut', duration: 0.6 },
      },
      animate: {
        y1: [10, 8.5, 10],
        y2: [10, 11.5, 10],
        transition: { ease: 'easeInOut', duration: 0.6 },
      },
    },
  } as Record<string, Variants>,
  },
  pulse: {
    elements: [
      { tag: "g", attrs: {}, key: "group", children: [
        { tag: "path", attrs: { d: "M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" }, key: "path" },
        { tag: "line", attrs: { x1: "16", y1: "10", x2: "16", y2: "10" }, key: "line1" },
        { tag: "line", attrs: { x1: "12", y1: "10", x2: "12", y2: "10" }, key: "line2" },
        { tag: "line", attrs: { x1: "8", y1: "10", x2: "8", y2: "10" }, key: "line3" },
      ] },
    ],
    variants: {
    group: {},
    path: {},
    line1: {
      initial: {
        scale: 1,
      },
      animate: {
        scale: [1, 1.5, 1],
        transition: {
          duration: 1,
          delay: 0.4,
          ease: 'easeInOut',
        },
      },
    },
    line2: {
      initial: {
        scale: 1,
      },
      animate: {
        scale: [1, 1.5, 1],
        transition: {
          duration: 1,
          delay: 0.2,
          ease: 'easeInOut',
        },
      },
    },
    line3: {
      initial: {
        scale: 1,
      },
      animate: {
        scale: [1, 1.5, 1],
        transition: {
          duration: 1,
          ease: 'easeInOut',
        },
      },
    },
  } as Record<string, Variants>,
  },
  jump: {
    elements: [
      { tag: "g", attrs: {}, key: "group", children: [
        { tag: "path", attrs: { d: "M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" }, key: "path" },
        { tag: "line", attrs: { x1: "16", y1: "10", x2: "16", y2: "10" }, key: "line1" },
        { tag: "line", attrs: { x1: "12", y1: "10", x2: "12", y2: "10" }, key: "line2" },
        { tag: "line", attrs: { x1: "8", y1: "10", x2: "8", y2: "10" }, key: "line3" },
      ] },
    ],
    variants: {
    group: {},
    path: {},
    line1: {
      initial: {
        y: 0,
      },
      animate: {
        y: [-0.75, 0.75],
        transition: {
          duration: 0.8,
          delay: 0.4,
          repeat: Infinity,
          repeatType: 'mirror',
          ease: 'easeInOut',
        },
      },
    },
    line2: {
      initial: {
        y: 0,
      },
      animate: {
        y: [-0.75, 0.75],
        transition: {
          duration: 0.8,
          delay: 0.2,
          repeat: Infinity,
          repeatType: 'mirror',
          ease: 'easeInOut',
        },
      },
    },
    line3: {
      initial: {
        y: 0,
      },
      animate: {
        y: [-0.75, 0.75],
        transition: {
          duration: 0.8,
          repeat: Infinity,
          repeatType: 'mirror',
          ease: 'easeInOut',
        },
      },
    },
  } as Record<string, Variants>,
  },
  alt: {
    elements: [
      { tag: "path", attrs: { d: "M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" } },
      { tag: "path", attrs: { custom: 0, d: "M8 10h.01" }, key: "dot" },
      { tag: "path", attrs: { custom: 1, d: "M12 10h.01" }, key: "dot" },
      { tag: "path", attrs: { custom: 2, d: "M16 10h.01" }, key: "dot" },
    ],
    variants: {
    dot: {
  initial: {
    opacity: 1,
  },
  animate: (custom: number) => ({
    opacity: [1, 0, 0, 1, 1, 0, 0, 1],
    transition: {
      opacity: {
        times: [
          0,
          0.1,
          0.1 + custom * 0.1,
          0.1 + custom * 0.1 + 0.1,
          0.5,
          0.6,
          0.6 + custom * 0.1,
          0.6 + custom * 0.1 + 0.1,
        ],
        duration: 1.5,
      },
    },
  }),
},
  } as Record<string, Variants>,
  },
}

const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <MessageSquareMore :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <MultiVariantIcon
    v-else
    :animations="animations"
    :size="props.size"
    :strokeWidth="props.strokeWidth"
  />
</template>
