<script setup lang="ts">
// Multi-variant icon. The original animate-ui / hand-written silhouette ships
// as `default` (plus any extra named animations the base SFC carried —
// `blink`, `wink`, `pulse`, etc.); the pqoqubbw/lucide-animated silhouette
// ships as `alt`. Element graphs differ across variants, so we delegate to
// `<MultiVariantIcon>` rather than the standard hand-templated layout.
//
// Generated by scripts/port-pqoqubbw-icons.mjs (multi-variant merge path).
// Hand-edits survive port reruns — the script preserves SFCs that already
// host an `alt` variant via this path.
import { computed } from 'vue'
import type { Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import MultiVariantIcon from '../core/MultiVariantIcon.vue'
import { hasOwnTriggers, type IconTriggerProps } from '../core/context'
import type { MultiVariantAnimations } from '../core/element-types'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations: MultiVariantAnimations = {
  default: {
    elements: [
      { tag: "path", attrs: { d: "M12 8V4H8" }, key: "path1" },
      { tag: "rect", attrs: { width: 16, height: 12, x: 4, y: 8, rx: 2 }, key: "rect" },
      { tag: "path", attrs: { d: "M2 14h2" }, key: "path2" },
      { tag: "path", attrs: { d: "M20 14h2" }, key: "path3" },
      { tag: "path", attrs: { d: "M15 13v2" }, key: "path4" },
      { tag: "path", attrs: { d: "M9 13v2" }, key: "path5" },
    ],
    variants: {
    path1: {},
    rect: {},
    path2: {},
    path3: {},
    path4: {
      initial: {
        x: 0,
        y: 0,
      },
      animate: {
        x: [0, -1.5, 1.5, 0],
        y: [0, 1.5, 1.5, 0],
        transition: {
          ease: 'easeInOut',
          duration: 1.3,
        },
      },
    },
    path5: {
      initial: {
        x: 0,
        y: 0,
      },
      animate: {
        x: [0, -1.5, 1.5, 0],
        y: [0, 1.5, 1.5, 0],
        transition: {
          ease: 'easeInOut',
          duration: 1.3,
        },
      },
    },
  } as Record<string, Variants>,
  },
  blink: {
    elements: [
      { tag: "path", attrs: { d: "M12 8V4H8" }, key: "path1" },
      { tag: "rect", attrs: { width: 16, height: 12, x: 4, y: 8, rx: 2 }, key: "rect" },
      { tag: "path", attrs: { d: "M2 14h2" }, key: "path2" },
      { tag: "path", attrs: { d: "M20 14h2" }, key: "path3" },
      { tag: "path", attrs: { d: "M15 13v2" }, key: "path4" },
      { tag: "path", attrs: { d: "M9 13v2" }, key: "path5" },
    ],
    variants: {
    path1: {},
    rect: {},
    path2: {},
    path3: {},
    path4: {
      initial: {
        scaleY: 1,
      },
      animate: {
        scaleY: [1, 0.5, 1],
        transition: {
          ease: 'easeInOut',
          duration: 0.6,
        },
      },
    },
    path5: {
      initial: {
        scaleY: 1,
      },
      animate: {
        scaleY: [1, 0.5, 1],
        transition: {
          ease: 'easeInOut',
          duration: 0.6,
        },
      },
    },
  } as Record<string, Variants>,
  },
  wink: {
    elements: [
      { tag: "path", attrs: { d: "M12 8V4H8" }, key: "path1" },
      { tag: "rect", attrs: { width: 16, height: 12, x: 4, y: 8, rx: 2 }, key: "rect" },
      { tag: "path", attrs: { d: "M2 14h2" }, key: "path2" },
      { tag: "path", attrs: { d: "M20 14h2" }, key: "path3" },
      { tag: "path", attrs: { d: "M15 13v2" }, key: "path4" },
      { tag: "path", attrs: { d: "M9 13v2" }, key: "path5" },
    ],
    variants: {
    path1: {},
    rect: {},
    path2: {},
    path3: {},
    path4: {
      initial: {
        scaleY: 1,
      },
      animate: {
        scaleY: [1, 0.5, 1],
        transition: {
          ease: 'easeInOut',
          duration: 0.6,
        },
      },
    },
    path5: {},
  } as Record<string, Variants>,
  },
  alt: {
    elements: [
      { tag: "path", attrs: { d: "M12 8V4H8" } },
      { tag: "rect", attrs: { height: "12", rx: "2", width: "16", x: "4", y: "8" } },
      { tag: "path", attrs: { d: "M2 14h2" } },
      { tag: "path", attrs: { d: "M20 14h2" } },
      { tag: "line", attrs: { x1: 15, x2: 15 }, key: "path" },
      { tag: "line", attrs: { x1: 9, x2: 9 }, key: "path" },
    ],
    variants: {
    path: {
              initial: { y1: 13, y2: 15 },
              animate: {
                y1: [13, 14, 13],
                y2: [15, 14, 15],
                transition: {
                  duration: 0.5,
                  ease: "easeInOut",
                  delay: 0.2,
                },
              },
            },
  } as Record<string, Variants>,
  },
}

const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <Bot :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <MultiVariantIcon
    v-else
    :animations="animations"
    :size="props.size"
    :strokeWidth="props.strokeWidth"
  />
</template>
