<script setup lang="ts">
// Auto-generated by Forge from a Claude proposal. Source: hand-written.
// Safe to hand-edit — port-icons.mjs only overwrites icons sourced from animate-ui.
import { computed } from 'vue'
import { motion, type Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import {
  getVariants,
  hasOwnTriggers,
  useAnimateIconContext,
  type IconTriggerProps,
} from '../core/context'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations = {
  default: {
    bulb: {
      initial: {
        opacity: 0.3,
      },
      animate: {
        opacity: [0.3, 1, 0.4, 1, 0.4, 1, 0.3],
        transition: {
          duration: 1.2,
          ease: "easeInOut",
        },
      },
    },
    rayR: {
      initial: {
        opacity: 0.3,
      },
      animate: {
        opacity: [0.3, 1, 0.3, 1, 0.3],
        transition: {
          duration: 1,
          ease: "easeInOut",
          delay: 0,
        },
      },
    },
    rayTR: {
      initial: {
        opacity: 0.3,
      },
      animate: {
        opacity: [0.3, 1, 0.3, 1, 0.3],
        transition: {
          duration: 1,
          ease: "easeInOut",
          delay: 0.1,
        },
      },
    },
    rayT: {
      initial: {
        opacity: 0.3,
      },
      animate: {
        opacity: [0.3, 1, 0.3, 1, 0.3],
        transition: {
          duration: 1,
          ease: "easeInOut",
          delay: 0.2,
        },
      },
    },
    rayTL: {
      initial: {
        opacity: 0.3,
      },
      animate: {
        opacity: [0.3, 1, 0.3, 1, 0.3],
        transition: {
          duration: 1,
          ease: "easeInOut",
          delay: 0.3,
        },
      },
    },
    rayL: {
      initial: {
        opacity: 0.3,
      },
      animate: {
        opacity: [0.3, 1, 0.3, 1, 0.3],
        transition: {
          duration: 1,
          ease: "easeInOut",
          delay: 0.4,
        },
      },
    },
  } satisfies Record<string, Variants>,
} satisfies Record<string, Record<string, Variants>>

const variants = getVariants(animations)
const { current, notifyComplete } = useAnimateIconContext()
const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <Siren :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <motion.svg
    v-else
    overflow="visible"
    style="user-select: none; -webkit-user-select: none"
    xmlns="http://www.w3.org/2000/svg"
    :width="props.size"
    :height="props.size"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    :stroke-width="props.strokeWidth"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
    <path
      d="M7 18v-6a5 5 0 1 1 10 0v6"
    />
    <path
      d="M5 21a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2z"
    />
    <motion.path
      d="M21 12h1"
      :variants="variants.rayR"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M18.5 4.5 18 5"
      :variants="variants.rayTR"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M2 12h1"
      :variants="variants.rayL"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M12 2v1"
      :variants="variants.rayT"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="m4.929 4.929.707.707"
      :variants="variants.rayTL"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M12 12v6"
      :variants="variants.bulb"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
  </motion.svg>
</template>
