<script setup lang="ts">
// Auto-generated by Forge from a Claude proposal. Source: hand-written.
// Safe to hand-edit — port-icons.mjs only overwrites icons sourced from animate-ui.
import { computed } from 'vue'
import { motion, type Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import {
  getVariants,
  hasOwnTriggers,
  useAnimateIconContext,
  type IconTriggerProps,
} from '../core/context'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations = {
  default: {
    canopy: {
      initial: {
        scaleY: 1,
        scaleX: 1,
      },
      animate: {
        scaleY: [1, 0.94, 1, 0.96, 1, 0.95, 1],
        scaleX: [1, 1.03, 1, 1.02, 1, 1.025, 1],
        transition: {
          duration: 1.6,
          ease: "easeInOut",
        },
      },
    },
    handle: {
      initial: {
        rotate: 0,
      },
      animate: {
        rotate: [0, 3, -2, 2, -1, 0],
        transition: {
          duration: 1.8,
          ease: "easeInOut",
        },
      },
    },
    "aux:drop1": {
      initial: {
        y: -8,
        opacity: 0,
      },
      animate: {
        y: [-8, 4],
        opacity: [0, 1, 1, 0],
        transition: {
          duration: 0.55,
          ease: "easeIn",
          delay: 0,
        },
      },
    },
    "aux:drop2": {
      initial: {
        y: -8,
        opacity: 0,
      },
      animate: {
        y: [-8, 4],
        opacity: [0, 1, 1, 0],
        transition: {
          duration: 0.6,
          ease: "easeIn",
          delay: 0.45,
        },
      },
    },
    "aux:drop3": {
      initial: {
        y: -8,
        opacity: 0,
      },
      animate: {
        y: [-8, 4],
        opacity: [0, 1, 1, 0],
        transition: {
          duration: 0.5,
          ease: "easeIn",
          delay: 0.9,
        },
      },
    },
  } satisfies Record<string, Variants>,
} satisfies Record<string, Record<string, Variants>>

const variants = getVariants(animations)
const { current, notifyComplete } = useAnimateIconContext()
const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <Umbrella :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <motion.svg
    v-else
    overflow="visible"
    style="user-select: none; -webkit-user-select: none"
    xmlns="http://www.w3.org/2000/svg"
    :width="props.size"
    :height="props.size"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    :stroke-width="props.strokeWidth"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
    <motion.path
      d="M12 13v7a2 2 0 0 0 4 0"
      style="transform-origin: 14px 13px"
      :variants="variants.handle"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <path
      d="M12 2v2"
    />
    <motion.path
      d="M20.992 13a1 1 0 0 0 .97-1.274 10.284 10.284 0 0 0-19.923 0A1 1 0 0 0 3 13z"
      style="transform-origin: 12px 12px"
      :variants="variants.canopy"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.line
      x1="6"
      y1="0"
      x2="6"
      y2="2"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      :variants="variants['aux:drop1']"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.line
      x1="12"
      y1="-2"
      x2="12"
      y2="0"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      :variants="variants['aux:drop2']"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.line
      x1="18"
      y1="0"
      x2="18"
      y2="2"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      :variants="variants['aux:drop3']"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
  </motion.svg>
</template>
