<script setup lang="ts">
// Multi-variant icon. The original animate-ui / hand-written silhouette ships
// as `default` (plus any extra named animations the base SFC carried —
// `blink`, `wink`, `pulse`, etc.); the pqoqubbw/lucide-animated silhouette
// ships as `alt`. Element graphs differ across variants, so we delegate to
// `<MultiVariantIcon>` rather than the standard hand-templated layout.
//
// Generated by scripts/port-pqoqubbw-icons.mjs (multi-variant merge path).
// Hand-edits survive port reruns — the script preserves SFCs that already
// host an `alt` variant via this path.
import { computed } from 'vue'
import type { Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import MultiVariantIcon from '../core/MultiVariantIcon.vue'
import { hasOwnTriggers, type IconTriggerProps } from '../core/context'
import type { MultiVariantAnimations } from '../core/element-types'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations: MultiVariantAnimations = {
  default: {
    elements: [
      { tag: "path", attrs: { d: "m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" }, key: "path" },
      { tag: "circle", attrs: { cx: 12, cy: 12, r: 10 }, key: "circle" },
    ],
    variants: {
    path: {
      initial: {
        rotate: 0,
      },
      animate: {
        rotate: [0, 95, 75],
        transition: {
          duration: 0.7,
          ease: 'easeInOut',
        },
      },
    },
    circle: {},
  } as Record<string, Variants>,
  },
  'default-loop': {
    elements: [
      { tag: "path", attrs: { d: "m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" }, key: "path" },
      { tag: "circle", attrs: { cx: 12, cy: 12, r: 10 }, key: "circle" },
    ],
    variants: {
    path: {
      initial: {
        rotate: 0,
      },
      animate: {
        rotate: [0, 95, 75, -20, 0],
        transition: {
          duration: 1.4,
          ease: 'easeInOut',
        },
      },
    },
    circle: {},
  } as Record<string, Variants>,
  },
  alt: {
    elements: [
      { tag: "circle", attrs: { cx: "12", cy: "12", r: "10" } },
      { tag: "polygon", attrs: { points: "16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76" }, key: "path" },
    ],
    variants: {
    path: {
              initial: {
                rotate: 0,
              },
              animate: {
                rotate: 360,
              },
            },
  } as Record<string, Variants>,
  },
}

const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <Compass :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <MultiVariantIcon
    v-else
    :animations="animations"
    :size="props.size"
    :strokeWidth="props.strokeWidth"
  />
</template>
