<script setup lang="ts">
// Multi-variant icon. The original animate-ui / hand-written silhouette ships
// as `default` (plus any extra named animations the base SFC carried —
// `blink`, `wink`, `pulse`, etc.); the pqoqubbw/lucide-animated silhouette
// ships as `alt`. Element graphs differ across variants, so we delegate to
// `<MultiVariantIcon>` rather than the standard hand-templated layout.
//
// Generated by scripts/port-pqoqubbw-icons.mjs (multi-variant merge path).
// Hand-edits survive port reruns — the script preserves SFCs that already
// host an `alt` variant via this path.
import { computed } from 'vue'
import type { Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import MultiVariantIcon from '../core/MultiVariantIcon.vue'
import { hasOwnTriggers, type IconTriggerProps } from '../core/context'
import type { MultiVariantAnimations } from '../core/element-types'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations: MultiVariantAnimations = {
  default: {
    elements: [
      { tag: "circle", attrs: { cx: "12", cy: "12", r: "4" }, key: "circle" },
      { tag: "line", attrs: { x1: "12", y1: "4", x2: "12", y2: "2" }, key: "line1" },
      { tag: "line", attrs: { x1: "17.7", y1: "6.3", x2: "19.1", y2: "4.9" }, key: "line2" },
      { tag: "line", attrs: { x1: "20", y1: "12", x2: "22", y2: "12" }, key: "line3" },
      { tag: "line", attrs: { x1: "17.7", y1: "17.7", x2: "19.1", y2: "19.1" }, key: "line4" },
      { tag: "line", attrs: { x1: "12", y1: "20", x2: "12", y2: "22" }, key: "line5" },
      { tag: "line", attrs: { x1: "6.3", y1: "17.7", x2: "4.9", y2: "19.1" }, key: "line6" },
      { tag: "line", attrs: { x1: "4", y1: "12", x2: "2", y2: "12" }, key: "line7" },
      { tag: "line", attrs: { x1: "6.3", y1: "6.3", x2: "4.9", y2: "4.9" }, key: "line8" },
    ],
    variants: (() => {
    const animation: Record<string, Variants> = {
      circle: {},
    };

    for (let i = 1; i <= 8; i++) {
      animation[`line${i}`] = {
        initial: { opacity: 1, scale: 1 },
        animate: {
          opacity: [0, 1],
          pathLength: [0, 1],
          transition: {
            duration: 0.6,
            ease: 'easeInOut',
            delay: (i - 1) * 0.15,
          },
        },
      };
    }

    return animation;
  })() as Record<string, Variants>,
  },
  alt: {
    elements: [
      { tag: "circle", attrs: { cx: "12", cy: "12", r: "4" } },
      { tag: "path", attrs: { d: "M12 2v2" }, key: "path1" },
      { tag: "path", attrs: { d: "m19.07 4.93-1.41 1.41" }, key: "path2" },
      { tag: "path", attrs: { d: "M20 12h2" }, key: "path3" },
      { tag: "path", attrs: { d: "m17.66 17.66 1.41 1.41" }, key: "path4" },
      { tag: "path", attrs: { d: "M12 20v2" }, key: "path5" },
      { tag: "path", attrs: { d: "m6.34 17.66-1.41 1.41" }, key: "path6" },
      { tag: "path", attrs: { d: "M2 12h2" }, key: "path7" },
      { tag: "path", attrs: { d: "m4.93 4.93 1.41 1.41" }, key: "path8" },
    ],
    variants: {
    path1: {
  initial: { opacity: 1 },
  animate: ((i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }))(1),
},
    path2: {
  initial: { opacity: 1 },
  animate: ((i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }))(2),
},
    path3: {
  initial: { opacity: 1 },
  animate: ((i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }))(3),
},
    path4: {
  initial: { opacity: 1 },
  animate: ((i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }))(4),
},
    path5: {
  initial: { opacity: 1 },
  animate: ((i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }))(5),
},
    path6: {
  initial: { opacity: 1 },
  animate: ((i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }))(6),
},
    path7: {
  initial: { opacity: 1 },
  animate: ((i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }))(7),
},
    path8: {
  initial: { opacity: 1 },
  animate: ((i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }))(8),
},
  } as Record<string, Variants>,
  },
}

const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <Sun :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <MultiVariantIcon
    v-else
    :animations="animations"
    :size="props.size"
    :strokeWidth="props.strokeWidth"
  />
</template>
