<script setup lang="ts">
// Multi-variant icon. The original animate-ui / hand-written silhouette ships
// as `default` (plus any extra named animations the base SFC carried —
// `blink`, `wink`, `pulse`, etc.); the pqoqubbw/lucide-animated silhouette
// ships as `alt`. Element graphs differ across variants, so we delegate to
// `<MultiVariantIcon>` rather than the standard hand-templated layout.
//
// Generated by scripts/port-pqoqubbw-icons.mjs (multi-variant merge path).
// Hand-edits survive port reruns — the script preserves SFCs that already
// host an `alt` variant via this path.
import { computed } from 'vue'
import type { Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import MultiVariantIcon from '../core/MultiVariantIcon.vue'
import { hasOwnTriggers, type IconTriggerProps } from '../core/context'
import type { MultiVariantAnimations } from '../core/element-types'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations: MultiVariantAnimations = {
  default: {
    elements: [
      { tag: "g", attrs: {}, key: "group", children: [
        { tag: "path", attrs: { d: "M12 6V2H8" }, key: "path1" },
        { tag: "path", attrs: { d: "m8 18-4 4V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2Z" }, key: "path2" },
        { tag: "path", attrs: { d: "M2 12h2" }, key: "path3" },
        { tag: "path", attrs: { d: "M9 11v2" }, key: "path4" },
        { tag: "path", attrs: { d: "M15 11v2" }, key: "path5" },
        { tag: "path", attrs: { d: "M20 12h2" }, key: "path6" },
      ] },
    ],
    variants: {
    group: {
      initial: {
        rotate: 0,
      },
      animate: {
        transformOrigin: 'bottom left',
        rotate: [0, 8, -8, 2, 0],
        transition: {
          ease: 'easeInOut',
          duration: 0.8,
          times: [0, 0.4, 0.6, 0.8, 1],
        },
      },
    },
    path1: {},
    path2: {},
    path3: {},
    path4: {
      initial: {
        scaleY: 1,
      },
      animate: {
        scaleY: [1, 0.5, 1],
        transition: {
          ease: 'easeInOut',
          duration: 0.6,
        },
      },
    },
    path5: {},
    path6: {},
  } as Record<string, Variants>,
  },
  'look-at': {
    elements: [
      { tag: "g", attrs: {}, key: "group", children: [
        { tag: "path", attrs: { d: "M12 6V2H8" }, key: "path1" },
        { tag: "path", attrs: { d: "m8 18-4 4V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2Z" }, key: "path2" },
        { tag: "path", attrs: { d: "M2 12h2" }, key: "path3" },
        { tag: "path", attrs: { d: "M9 11v2" }, key: "path4" },
        { tag: "path", attrs: { d: "M15 11v2" }, key: "path5" },
        { tag: "path", attrs: { d: "M20 12h2" }, key: "path6" },
      ] },
    ],
    variants: {
    group: {},
    path1: {},
    path2: {},
    path3: {},
    path4: {
      initial: {
        x: 0,
        y: 0,
      },
      animate: {
        x: [0, -1.5, 1.5, 0],
        y: [0, 1.5, 1.5, 0],
        transition: {
          ease: 'easeInOut',
          duration: 1.3,
        },
      },
    },
    path5: {
      initial: {
        x: 0,
        y: 0,
      },
      animate: {
        x: [0, -1.5, 1.5, 0],
        y: [0, 1.5, 1.5, 0],
        transition: {
          ease: 'easeInOut',
          duration: 1.3,
        },
      },
    },
    path6: {},
  } as Record<string, Variants>,
  },
  blink: {
    elements: [
      { tag: "g", attrs: {}, key: "group", children: [
        { tag: "path", attrs: { d: "M12 6V2H8" }, key: "path1" },
        { tag: "path", attrs: { d: "m8 18-4 4V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2Z" }, key: "path2" },
        { tag: "path", attrs: { d: "M2 12h2" }, key: "path3" },
        { tag: "path", attrs: { d: "M9 11v2" }, key: "path4" },
        { tag: "path", attrs: { d: "M15 11v2" }, key: "path5" },
        { tag: "path", attrs: { d: "M20 12h2" }, key: "path6" },
      ] },
    ],
    variants: {
    group: {},
    path1: {},
    path2: {},
    path3: {},
    path4: {
      initial: {
        scaleY: 1,
      },
      animate: {
        scaleY: [1, 0.5, 1],
        transition: {
          ease: 'easeInOut',
          duration: 0.6,
        },
      },
    },
    path5: {
      initial: {
        scaleY: 1,
      },
      animate: {
        scaleY: [1, 0.5, 1],
        transition: {
          ease: 'easeInOut',
          duration: 0.6,
        },
      },
    },
    path6: {},
  } as Record<string, Variants>,
  },
  wink: {
    elements: [
      { tag: "g", attrs: {}, key: "group", children: [
        { tag: "path", attrs: { d: "M12 6V2H8" }, key: "path1" },
        { tag: "path", attrs: { d: "m8 18-4 4V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2Z" }, key: "path2" },
        { tag: "path", attrs: { d: "M2 12h2" }, key: "path3" },
        { tag: "path", attrs: { d: "M9 11v2" }, key: "path4" },
        { tag: "path", attrs: { d: "M15 11v2" }, key: "path5" },
        { tag: "path", attrs: { d: "M20 12h2" }, key: "path6" },
      ] },
    ],
    variants: {
    group: {},
    path1: {},
    path2: {},
    path3: {},
    path4: {},
    path5: {
      initial: {
        scaleY: 1,
      },
      animate: {
        scaleY: [1, 0.5, 1],
        transition: {
          ease: 'easeInOut',
          duration: 0.6,
        },
      },
    },
    path6: {},
  } as Record<string, Variants>,
  },
  alt: {
    elements: [
      { tag: "g", attrs: {}, key: "path", children: [
        { tag: "path", attrs: { d: "M12 6V2H8" } },
        { tag: "path", attrs: { d: "M2 12h2" } },
        { tag: "path", attrs: { d: "M20 12h2" } },
        { tag: "path", attrs: { d: "M20 16a2 2 0 0 1-2 2H8.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 4 20.286V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2z" }, key: "path2" },
        { tag: "path", attrs: { d: "M9 11v2" }, key: "path3" },
        { tag: "path", attrs: { d: "M15 11v2" }, key: "path4" },
        { tag: "circle", attrs: { cx: "10", cy: "18", r: "0.5" }, key: "path5" },
        { tag: "circle", attrs: { cx: "12", cy: "18", r: "0.5" }, key: "path6" },
        { tag: "circle", attrs: { cx: "14", cy: "18", r: "0.5" }, key: "path7" },
      ] },
    ],
    variants: {
    path: {
          initial: { rotate: 0, y: 0, scale: 1 },
          animate: {
            rotate: [0, -3, 3, 0, 0],
            y: [0, 1.5, -1.5, 0],
            scale: [1, 1.03, 1],
            transition: {
              duration: 1,
              ease: "easeInOut",
              repeat: 0,
            },
          },
        },
    path2: {
            initial: { scale: 1, originX: 0.5, originY: 0.5 },
            animate: {
              scale: [1, 1.04, 1],
              transition: {
                duration: 0.6,
                ease: "easeInOut",
                repeat: 1,
              },
            },
          },
    path3: {
            initial: { scaleY: 1, originY: 0.5 },
            animate: {
              scaleY: [1, 0.1, 1],
              transition: { duration: 0.4, ease: "easeInOut", delay: 0.1 },
            },
          },
    path4: {
            initial: { scaleY: 1, originY: 0.5 },
            animate: {
              scaleY: [1, 0.1, 1],
              transition: { duration: 0.4, ease: "easeInOut", delay: 0.2 },
            },
          },
    path5: {
            initial: { opacity: 0 },
            animate: {
              opacity: [0.3, 1, 0.3],
              transition: {
                repeat: Number.POSITIVE_INFINITY,
                duration: 1.2,
                delay: 0,
              },
            },
          },
    path6: {
            initial: { opacity: 0 },
            animate: {
              opacity: [0.3, 1, 0.3],
              transition: {
                repeat: Number.POSITIVE_INFINITY,
                duration: 1.2,
                delay: 0.3,
              },
            },
          },
    path7: {
            initial: { opacity: 0 },
            animate: {
              opacity: [0.3, 1, 0.3],
              transition: {
                repeat: Number.POSITIVE_INFINITY,
                duration: 1.2,
                delay: 0.6,
              },
            },
          },
  } as Record<string, Variants>,
  },
}

const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <BotMessageSquare :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <MultiVariantIcon
    v-else
    :animations="animations"
    :size="props.size"
    :strokeWidth="props.strokeWidth"
  />
</template>
