<script setup lang="ts">
// Auto-generated by Forge from a Claude proposal. Source: hand-written.
// Safe to hand-edit — port-icons.mjs only overwrites icons sourced from animate-ui.
import { computed } from 'vue'
import { motion, type Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import {
  getVariants,
  hasOwnTriggers,
  useAnimateIconContext,
  type IconTriggerProps,
} from '../core/context'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations = {
  default: {
    heart: {
      initial: {
        scale: 1,
      },
      animate: {
        scale: [1, 1.15, 1, 1.18, 1],
        transition: {
          duration: 1.1,
          ease: "easeInOut",
          times: [0, 0.18, 0.4, 0.6, 1],
        },
      },
    },
    pulse: {
      initial: {
        pathLength: 0,
        opacity: 0.4,
      },
      animate: {
        pathLength: [0, 0, 1],
        opacity: [0.4, 1, 1],
        transition: {
          duration: 1.3,
          ease: "easeOut",
          times: [0, 0.15, 1],
        },
      },
    },
  } satisfies Record<string, Variants>,
} satisfies Record<string, Record<string, Variants>>

const variants = getVariants(animations)
const { current, notifyComplete } = useAnimateIconContext()
const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <HeartPulse :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <motion.svg
    v-else
    overflow="visible"
    style="user-select: none; -webkit-user-select: none"
    xmlns="http://www.w3.org/2000/svg"
    :width="props.size"
    :height="props.size"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    :stroke-width="props.strokeWidth"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
    <motion.path
      d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"
      style="transform-origin: 12px 13.08px"
      :variants="variants.heart"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
    <motion.path
      d="M3.22 13H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27"
      :variants="variants.pulse"
      initial="initial"
      :animate="current"
      @animationComplete="notifyComplete"
    />
  </motion.svg>
</template>
